# Generated by Django 5.0 on 2023-12-11 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_project_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
