# Generated by Django 5.0 on 2023-12-11 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='created_at',
        ),
    ]
